### ISSUE TITLE
Missing "release" on GitHub

### ISSUE THREAD

**Issue by mattwthompson** [yt-project/unyt#112]
I don't know how impactful this is but I noticed `unyt` 2.4 isn't "released" here on GitHub but it seems to be distributed elsewhere:

https://github.com/yt-project/unyt/releases
https://anaconda.org/conda-forge/unyt
https://pypi.org/project/unyt/

Just noticed this discrepancy while comparing different behavior across two users

**Comment by ngoldbaum** [comment]
Oh oops. I forgot to the github release. I only did it once because JOSS insisted on it but now I have to do it every time because people seem to rely on it...

If you're using the tarballs from github, please don't, use pypi instead. I wish I could avoid using github's release functionality because it means there are two places to download releases and I'd prefer to avoid that.

Thanks for the report :)

I'm closing this and I'll do the release right now.

**Comment by mattwthompson** [comment]
I use conda/pip for the actual source code, I pretty much only ended up there for the bookkeeping of asking "what's the most recent version?" which could have just as easily been done on pypi/anaconda sites. I understand your frustration, it is an extra step for not much benefit.

**Comment by ngoldbaum** [comment]
It looks like I forgot to push the v2.4.0 tag to github too (argh, dumb). So thank you for the report! Would have been bad if I'd lost my laptop or something....
