### ISSUE TITLE
Implement __call__ on `unyt_array` and `unyt_quantity`? 

### ISSUE THREAD

**Issue by jzuhone** [yt-project/unyt#167]
I saw that for the Julia units package `Unitful` that a unit conversion can be carried out simply using a call operation:

http://painterqubits.github.io/Unitful.jl/stable/conversion/

So in unyt this would look like:

```python
import unyt as u
a = 100.0*u.cm
print(a("m"))
1 m
```
It's a bit obtuse, but it could also be very handy for long code lines. It would be pretty simple to implement also. 

What do you think @ngoldbaum?

**Comment by ngoldbaum** [comment]
I’m not really a huge fan of adding concise but confusing syntax. A naive reader of that code would be confused by the function call syntax, I think, since there’s no way to infer the semantic meaning without either making a lucky guess or looking it up in the docs. I’d also not really be terribly happy with adding a second synonym for `in_units`. To be honest I think `.to()` is also too concise but the ship has sailed on that one.
