### ISSUE TITLE
User-defined units not as precise?

### ISSUE THREAD

**Issue by ThoAppelsin** [yt-project/unyt#168]
* unyt version: 2.7.2
* Python version: 3.8.5
* Operating System: Windows 10.0.18363

### Description

I wanted to declare `liter` as a unit. Noticed a blatant imprecision as I tested it crudely.

### What I Did

Outputs are given as comments:

```
import unyt

print((1*unyt.m**3).to('dm**3'))
# 1000.0 dm**3

unyt.define_unit("l", 1*unyt.dm**3)
print((1*unyt.m**3).to('l'))
# 999.99994 l
```

### What I'd Expect

I'd expect the two to be precisely equal, as I had defined them to be precisely equal.

**Comment by neutrinoceros** [comment]
Indeed the result on MacOS 11.5.1 with unyt 2.7.2 + numpy 1.19.2 is similar to that on Ubuntu 18 as reported by @l-johnston.
Note that unyt provides `unyt.testing.assert_allclose_units` and `unyt.allclose_unit`, which allows you to compare unitful arrays within a controllable absolute or relative tolerance.
Underneath, `unyt_array.to` forces a conversion to floats because most unit conversions can't be reliably performed with integers, which makes it subject to floating point errors. I do not think there's anything we can do about it on unyt's side.
