### ISSUE TITLE
String to Unyt and auto reduce units

### ISSUE THREAD

**Issue by GitterHubber** [yt-project/unyt#181]
* unyt version: 2.8.0
* Python version: 3.6.8
* Operating System: Windows 7 x64, SP1

1. Does unyt has a auto reduce function like pint?
![image](https://user-images.githubusercontent.com/2816034/100526429-e2ae8e00-31ee-11eb-8eec-fa1ffcd28741.png)
as can be seen in the image, when I multiply units for 2 different types like cm and inch i get a result unit like "cm * inch"
can this be autoreduced to "cm" since they are both of the same quantity "length" ?

2. Does unyt support parsing string to units.
like if I have a string unit like 'm/s' does unyt have any functionality to convert into a unyt compatible object?

TIA

**Comment by ngoldbaum** [comment]
1. No, since the answer would depend on the order of operations. However if you do something like cm/inches you’ll get a dimensionless result.

2. Yes:

```
from unyt import Unit, unyt_array

u = Unit(‘m/s’)

print(3*u)

# these are synonyms
print([1, 2, 3]*u)
print(unyt_array([1, 2, 3], u)
```

**Comment by JBorrow** [comment]
A quick comment on your 1. - the result of v1 * v2 has units of area (as unyt says, this is correctly inch centimetres). You can convert this to cm^2 if you like by doing `.to("cm**2")`.

In the docs, there is information on simplifying units. You can find that here: https://unyt.readthedocs.io/en/stable/usage.html?highlight=simplify#simplifying-units

**Comment by GitterHubber** [comment]
Thanks for the info.
Since the calls are going to be dynamic, i may have to do a check each time to convert the units from a compound type like "inch centimeters" to cm^2.
Why doesn't unyt auto simplify like pint does?

**Comment by ngoldbaum** [comment]
It might help if you could explain a little more what behavior you’d like to see, maybe with an illustrative example? Assume we don’t know anything about Pint :)

If I understand what you’re suggesting, you want the result of operations to depend on the order of the operands, so if you did `v1*v2` you’d get an answer in cm^2 but if you did `v2*v1` you’d get an answer in in^2. As I said before we don’t do that because IMO it’s more surprising for the value of a multiplicative quantity to depend on the order of the operands than it is to need to deal with compound units.

I’m also personally not a big fan of user-controllable toggles for how unyt should behave, since that might set up a situation where two different codebases make use of unyt, make different choices, and mutually break each other when you try to use them together. unyt does have a way to provide customization for library authors who wrap unyt but the idea is the library author would expose their own wrapper for unyt and not the top-level unyt module itself and you could implement you suggestion e.g. by adding a new flag to the `UnitRegistry` class and maybe a check or two elsewhere in the codebase.

If you want both operations to give you back something in cm^2, maybe you just want the `in_cgs` or `in_base` methods instead?

The reason the library does or doesn’t do something is almost always because no one has implemented it. If you feel like unyt should behave differently somehow I invite you to try your hand at implementing the feature, just keep the contribution guidelines in mind.
