### ISSUE TITLE
unyt.array.allclose_units() not working as expected for arrays of complex numbers

### ISSUE THREAD

**Issue by gregsalvesen-work** [yt-project/unyt#223]
* unyt version: 2.8.0
* Python version: 3.9.10
* Operating System: macOS Big Sur

`unyt.array.allclose_units()` is not working as I expected for arrays of complex numbers.

```
import numpy as np
import unyt as u
a = np.random.standard_normal(100) * u.dimensionless
A = np.fft.fft(a) * u.dimensionless
print(np.allclose(A, A))
True
print(u.array.allclose_units(A, A))
False
```
and gives the warning:
```
/usr/local/lib/python3.9/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
```

**Comment by neutrinoceros** [comment]
I can reproduce this with unyt 2.8.0 + numpy 1.22
However it seems that the issue is already solved on unyt's dev branch:

```python
>>> print(u.array.allclose_units(A, A))
True
```
also numpy emits no warning.
Sorry the change hasn't made it into a release yet. If you want to rely on this working correctly I suggest installing unyt from source for now. I'll close.
