### ISSUE TITLE
`u.dimensions.args` is incorrect if there is only one dimension

### ISSUE THREAD

**Issue by jgunstone** [yt-project/unyt#263]
* unyt version: 2.9.2
* Python version: 3.9.7
* Operating System: Ubuntu 20.04 LTS

### Description

`u.dimensions.args` is an empty tuple if `len(u.dimensions.args)` should be 1

### What I Did

```py
import unyt as u

myunit = u.m
display(myunit.dimensions)  # = length
display(myunit.dimensions.args) # = ()  BUG!!. expected ((length))
print('')
print('--------')
print('')
myunit = u.m / u.s
display(myunit.dimensions) # = length / time
display(myunit.dimensions.args) # ((length), 1/(time))  AS EXPECTED
```

![image](https://user-images.githubusercontent.com/21370980/181206420-038a37d0-91ec-433c-84b0-f8030d0e80df.png)

**Comment by neutrinoceros** [comment]
It is not clear to me what you are trying to achieve here. `myunit.dimensions` is `sympy.Symbol` object, and I don't think that accessing its `args` attribute is documented as something supported in unyt. I would tend to think of it as an implementation detail rather than a observable and reliable behaviour. It's also not obvious to me that builtin symbols *should* have a non-empty `args` attribute.

Can you clarify what you're trying to do on a broader level, or explain why you expect this attribute to be set for builtin symbols ?

**Comment by jgunstone** [comment]
hi there, thanks for the response. 
I'm using `unyt` to make an App using Voila. 
The App can be used to derive units for physical quantities, and it outputs a dict that adheres to IFC4.3 datafields for specifying physical dimensions. 
http://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcDimensionalExponents.htm

this is a simple mapping when the `unit.dimensions.args` fields are available as a tuple, as the details in the `args` tuple contain all of the "IfcDimensionalExponents" information. 
![unyt_deriver-bug](https://user-images.githubusercontent.com/21370980/181303834-36d175d4-af5f-42cb-9bef-9450c61a227c.gif)

> It's also not obvious to me that builtin symbols should have a non-empty args attribute.

Intuitively it seems like `unit.dimensions.args` should not be behaving in the way demonstrated above.
In all other cases, `unit.dimensions.args` returns a tuple of the base dimensions that define the unit. 
if the unit has a base dimension to the power 1, then it clearly does have a dimension.  
as such it is is unexpected (faulty?) behaviour that it returns an empty tuple.  
(I realise that my explanation conveniently ignores implementation details (as I don't have much understanding about whats going on under-the-hood) and instead focuses on expected API behaviour).

**Comment by neutrinoceros** [comment]
I looked it up some more and I am reasonably confident that, within unyt, just *having* the `args` attribute is a side effects rather than a designed property. It's coming from the fact that the `dimensions` attribute of a `Unit` object is really a sympy expression. I think this means you need to either search sympy's documentation or discuss with its devs if that doesn't help.

Meanwhile here's what I could grasp:
the fundamental difference between `u.m / u.s` and `u.m` in your example is that the former is a `sympy.Mul` object, and has a non empty `args` attribute populated with `sympy.Symbol` instances, while the latter *is* a `sympy.Symbol` instance itself.
I don't know much about sympy details, but I suspect that changing the behaviour of `Symbol` to do what you expect (contain itself ?) could be dramatic in other applications of sympy (creating infinite loops seems easy), and in any case it's very much out of our hands.

I think you what you really need is to work around the difference and do something like
```python
dim = u.dimensions
if isinstance(dim, Symbol):
    factors = (dim,)
else:
    factors = dim.args
```
Does this help ?

**Comment by matthewturk** [comment]
@jgunstone That app looks just *awesome*!!  Is there a place I can learn more about it?

**Comment by jgunstone** [comment]
> Does this help ?

yes, thank you. I ended up with something similar but yours is simpler so I'll use that. Thanks for looking into it and providing the clear explanation, much appreciated. 

> @jgunstone That app looks just awesome!! Is there a place I can learn more about it?

thanks very much! the repo is currently private and depends on some packages not yet public... though I'm expecting to make it public in the near-ish future... watch this space.
