### ISSUE TITLE
MNT: out of date copyright headers

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/unyt#349]
A bunch of files have a copyright header. Most of them use `# Copyright (c) 2018, yt Development Team.`, but some are on `# Copyright (c) 2019 ...` and even one `# Copyright (c) 2013 ...`.
The LICENSE file itself uses a different header `Copyright (c) 2018, Nathan Goldbaum`.
It would be easy to uniformise those and keep up to date with a pre-commit hook such as `insert-license` from https://github.com/Lucas-C/pre-commit-hooks (I've been using it for a couple years on another project, never had any issues with it). I'm happy to do it, I would just like to know if that's desired. If not, should we simply take these headers out ?

**Comment by ngoldbaum** [comment]
The license file probably shouldn’t assert I own the copyright, it should probably just follow whatever yt’s license has.

I would slightly prefer just dropping the years from the copyright statements or removing them entirely since the actual copyrights don’t depend on the headers existing. The one in the license file is sufficient probably.

Adding a new hook to do it is also fine but I’m not a big fan of dealing with noisy regular PRs, even once a year.
