### ISSUE TITLE
Include nautical miles (length) and knots (speed)

### ISSUE THREAD

**Issue by ring-michael** [yt-project/unyt#439]
* unyt version:
* Python version:
* Operating System:

### Description

First of all a very nice package which helps a lot and I like using it in my code. However, I just ran into the issue that I needed nautical miles and knots. I guess it takes one of the developers only a few moments to include thos two units and it would be very nice if you could do that. As abbreviation for both units I would suggest NM, or nmi for nautical miles (as suggested in wikipedia: https://en.wikipedia.org/wiki/Nautical_mile)t. I am used to nm but that will get confused with nanometers and is therefore not an option. For knots I would suggest kt (https://en.wikipedia.org/wiki/Knot_(unit)).

**Comment by neutrinoceros** [comment]
You'd be surprised how little time we actually have; none of us is getting paid for maintaining unyt.

A pull request adding these units would be most welcome, however.

**Comment by chrishavlin** [comment]
In case you missed it in the docs, you can also create your own units -- see the section on [User-Defined Units](https://unyt.readthedocs.io/en/stable/usage.html#user-defined-units). So depending on what you need nautical miles and knots for, might be simplest to just define those units dynamically when you need them rather rather than adding them to the base unyt package (I'm not trying to dissuade you from submitting a PR here! just wanted to make sure you were aware of this option).

**Comment by neutrinoceros** [comment]
Thanks Chris ! I really should have mentioned it. Next time I'm take my coffee *before* I answer to feature requests ;)
