### ISSUE TITLE
`unyt.amu` is a quantity, but `amu` is a built-in unit name as well.

### ISSUE THREAD

**Issue by chrisjonesBSU** [yt-project/unyt#440]
* unyt version: 2.9.5
* Python version: 3.11.4
* Operating System: MacOS (Intel)

### Description

I have a couple questions about the behavior of the `amu` unit.

### What I Did

First question: Why is the data type of amu different than other units like g, kg, g/mol, mm etc?

```
>>> import unyt as u

>>> type(u.amu)
<class 'unyt.array.unyt_quantity'>

>>> type(u.mg)
<class 'unyt.unit_object.Unit'>

>>> type(u.g/u.mol)
<class 'unyt.unit_object.Unit'>

>>> type(u.mm)
<class 'unyt.unit_object.Unit'>
```

Second question: When I try to create a new quantity with units of amu, the behavior is different than what I would expect. I get a unyt quantity in `kg` instead of `amu`

```
>>> 2.3 * u.amu
unyt_quantity(3.81923952e-27, 'kg')

>>> 2.3 * u.g
unyt_quantity(2.3, 'g')

>>> 2.3 * u.g/u.mol
unyt_quantity(2.3, 'g/mol')
```

I would expect that `2.3 * u.amu` would return `unyt_quantity(2.3, 'amu')`

It seems to work if I use `.to("amu")`. For example:

```
>>> 2.3 * u.amu.to("amu")
unyt_quantity(2.3, 'amu')
```

Is there something I'm missing about how Unyt handles amu compared to other mass units? 

Thanks!

**Comment by ngoldbaum** [comment]
Hmm, this is an oversight in the library. 

The top-level `unyt` namespace is populated with both `Unit` objects, as you saw, and `unyt_quantity` objects, which are the unyt equivalent of numpy scalars - a single numeric value that has a unit attached. Things like `unyt.msun` are quantities, but `unyt.gram` are units.

I guess at some point AMU was defined only as a quantity, then subsequently it got added as a unit name as well and no one removed it as a quantity, so it shows up in the top-level namespace as a quantity. We should probably only have it show up as a unit, I think that's unambiguously more useful and should be backward compatible, but whoever does that should think carefully if that really is the case.

We should also probably add a check to make sure there aren't any duplicate names in the sets of built-in unit names and quantity names as well.

For your purposes, you can get a `Unit` object for AMU like so:

```
>>> from unyt import Unit
>>> amu = Unit('amu')
```
or

```
>>> from unyt import amu
>>> amu = amu.unit
```

**Comment by jzuhone** [comment]
It turns out this is a bigger issue than just `amu`. The set intersection between the physical constants and the unit symbols in the namespace is:

```python
{'t_pl', 'c', 'm_pl', 'Mearth', 'l_pl', 'q_pl', 'E_pl', 'Msun', 'G', 'amu', 'Mjup', 'me', 'hbar', 'T_pl', 'mp'}
```

(`hbar` is funny because as a constant it's the reduced Planck constant but as a unit it's hectobar, a unit of pressure)

Currently thinking through how to resolve this...

**Comment by neutrinoceros** [comment]
One way forward could be to
- have an explicitly documented rule that when a name matches both a unit and a constant, the constant (or the unit) is the one that gets a seat in the top level namespace. (I don't have a strong personal preference, so I'd advise keeping the current behavior)
- recommend using lower level namespaces explicitly when writing code that's meant to be forward compatible.

This would be simple enough to implement and document. Within this approach we cannot guarantee stability of the top level namespace for constants and units at the same time, which is too bad, but this is the best solution I can think of which doesn't involve removing all units and/or all constants from the top level namespace.

**Comment by jzuhone** [comment]
> have an explicitly documented rule that when a name matches both a unit and a constant, the constant (or the unit) is the one that gets a seat in the top level namespace. (I don't have a strong personal preference, so I'd advise keeping the current behavior)

The current behavior is set more or less by the fact that physical constants get added after the unit symbols, so that means the former gets priority. My current plan for how to handle this is as follows:

* Remove `amu` as a physical constant, as it doesn't really make much sense as one anyway, so the top-level namespace will see it only as a unit symbol
* `G` is a tough one. Here, the Newtonian gravitational physical constant `G` is overriding the magnetic field unit symbol `G`, which is the same as `gauss`. One could simply say that we export `G` at the top level for the Newton constant and if someone wants the magnetic field unit from the top level, they have to use `gauss` instead. Of course then you have the funny situation that prefixed units like `μG` are still available from the top level. 
* The rest of the symbols in that list are properly physical constants and should probably just remain being the primary ones that are exported.

**Comment by neutrinoceros** [comment]
> The current behavior is set more or less by the fact that physical constants get added after the unit symbols, so that means the former gets priority

Yes. What I'm proposing is to make this a documented promise of the API.

**Comment by chrisjonesBSU** [comment]
Closing this with #459 merged.
