### ISSUE TITLE
Different results when calculating large (or small) numbers with and without units 

### ISSUE THREAD

**Issue by jo2267** [yt-project/unyt#451]
* unyt version: 2.9.5
* Python version: Python 3.11.5 from Anaconda [MSC v.1916 64 bit (AMD64)] on win32
* Operating System: Windows 11

### Description

a function treating large numbers give different results with and without units.

### What I Did

```
def test(a,b):
    return 4*b**4  + 8*a*b**3

print(test(100*u.micrometer, 120*u.micrometer))
print(test(100, 120))
```

With units, I get -2083127296 μm**4, while I get 2211840000 without units.

Is there anything specific I need to be careful when calculating large (or small) numbers with unyt?

**Comment by neutrinoceros** [comment]
This looks like integer overflow. `unyt_array`s (which are created implicitly in your example) use fixed-size integer representation internally, but Python integers can be of arbitrary size.

I think on win32 you'll get 32-bits integers by default, and the highest value that can correctly be represented in this type is `2147483647`. The correct result of your computation being greater than that, you get an overflow. You'd see the same behaviour if you tried your computation with pure numpy arrays.
The way to work around it is to specify a bigger integer size explicitly: 
instead of `100*u.micrometer`, use `u.unyt_quantity(100, "micrometer", dtype=np.int64)`

**Comment by jo2267** [comment]
Thanks a lot for the quick answer! This resolves the issue and my question.  :)
