### ISSUE TITLE
decorator for checking dimensions

### ISSUE THREAD

**Issue by berceanu** [yt-project/unyt#91]
Might I interest you guys in a decorator for ensuring correct dimensionality of function arguments?
Here's the [code](https://gist.github.com/berceanu/8516cb648e68e47c2d2298cd473f5f71), I use it in my project already. If interested, I can clean it up and submit a PR, let me know :)

**Comment by berceanu** [comment]
One thing I haven't figured out is how to test for dimensions like '1 / length', '1 / time' etc.

**Comment by ngoldbaum** [comment]
You could let your decorator take dimension objects, e.g.:

```
from unyt.dimensions import length, dimensionless

@check_dimensions(a=1/length, b=dimensionless)
def foo(a, b):
    ...
```

This could definitely be added to the library. It would need tests that cover all the lines in the code you're adding and docs. The docstrings would also need to be reformatted to be in numpy format like the rest of the docstrings in unyt. The docs can actually *be* the tests if you want because we use doctests heavily.

You might also want to consider using [`functools.wraps`](https://docs.python.org/3/library/functools.html#functools.wraps) which handles copying `__name__` and `__doc__` to the wrapped function.

**Comment by berceanu** [comment]
Which file would I add this to?

**Comment by ngoldbaum** [comment]
I'm not sure offhand, where do you think it would make the most sense? Perhaps in `unyt.dimensions` since it's checking dimensions? It should proably also get re-exported to the top-level `unyt` namespace.

**Comment by berceanu** [comment]
If you're still interested I'd like to proceed with this PR.

**Comment by ngoldbaum** [comment]
Go ahead :)

**Comment by berceanu** [comment]
https://github.com/yt-project/unyt/pull/98
