### ISSUE TITLE
add two temperature values in celcius and Kelvin

### ISSUE THREAD

**Issue by cyrillemidingoyi** [yt-project/unyt#99]
* unyt version:  2.2.2
* Python version:   3.7.1
* Operating System: Windows

I just add two temperature values in celcius and Kelvin.
But the result in celcius is wrong

In [16]: from unyt import celcius, K
In [17]: temp1 = 10*celcius
In [18]: temp2 = 1*K
In [19]: temp1+temp2
Out[19]: unyt_quantity(11, 'degC')

Result expected: unyt_quantity(-262,15, 'degC')

**Comment by ksunden** [comment]
Temperature is... weird.
There are different 0 marks for the different scales, therefore adding temperatures is not commutative.
If I start with 10 C and add 1 K, the result is quite right to be 11 C, but if I start with 1 K and add 10 C, that would be 11 K (or -262.15 C)

```
>>> t1  = 10 * unyt.degC
>>> t2 = 1* unyt.K
>>> t1+t2
unyt_quantity(11., 'degC')
>>> t2+t1
unyt_quantity(11., 'K')
```

Similarly, converting units causes strange behavior with temperature units, as the conversion breaks the idea of that being a difference:

```
>>> t1  = 10 * unyt.degC
>>> t2  = 10 * unyt.degC
>>> t1+t2
unyt_quantity(20., 'degC')
>>> t2.convert_to_base()
>>> t2
unyt_quantity(283.15, 'K')
>>> t1+t2
unyt_quantity(293.15, 'degC')
```


Unyt appears to resolve this (in the case of degC and K) by saying the left expression is the baseline, and the right is a temperature _difference_.
I know of other unit handlers that make explicit other "dimensions" for temperature difference vs absolute temperature.

Unyt explicitly forbids doing arithmetic on Fahrenheit or Celsius in other cases:

```
>>> t1 = 10*unyt.degF
>>> t2 = 10*unyt.K
>>> t1+t2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kyle/venvs/source/unyt/unyt/array.py", line 1630, in __array_ufunc__
    "Quantities with units of Fahrenheit or Celsius "
unyt.exceptions.InvalidUnitOperation: Quantities with units of Fahrenheit or Celsius cannot by multiplied, divided, subtracted or added with data that has different units.
```

The case of mixing degC and K is common enough (since they are the same step size) that adding and subtracting is excepted, but not commutative.
A similar exception exists for Fahrenheit and Rankine.

**Comment by ngoldbaum** [comment]
Thanks for summarizing @ksunden, couldn't have said it better myself.

That said it's certainly confusing and I think there's probably room for deprecating these operations, making them raise a user-visible warning and then an `InvalidUnitOperation` after a few releases. Following e.g. Pint we could define temperature delta units as well to make up for the loss of functionality.
